# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pipeline_showcase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QLabel, QVBoxLayout, QWidget, QPushButton
import os
from PyQt5.QtGui import QPixmap
import sys
from os.path import dirname, realpath, join
from PyQt5.QtWidgets import QWidget
from PyQt5.uic import loadUiType
import pandas as pd
from PyQt5 import QtWidgets

scriptDir = dirname(realpath(__file__))
From_Main, _ = loadUiType(join(dirname(__file__), "pipeline_showcase.ui"))

class Ui_pipeline(QWidget, From_Main):
    def setupUi(self, pipeline):
        pipeline.setObjectName("pipeline")
        pipeline.resize(1200, 800)
        self.pipelineLabel = QtWidgets.QLabel(pipeline)
        self.pipelineLabel.setGeometry(QtCore.QRect(110, 30, 1011, 611))
        self.pipelineLabel.setText("")
        self.pipelineLabel.setObjectName("pipelineLabel")
        self.pushButton = QtWidgets.QPushButton(pipeline)
        self.pushButton.setGeometry(QtCore.QRect(480, 710, 251, 51))
        self.pushButton.setObjectName("pushButton")

        # loading image
        self.pixmap = QPixmap("src\Pipeline.png")
 
        # adding image to label
        self.pipelineLabel.setPixmap(self.pixmap)

        self.retranslateUi(pipeline)
        QtCore.QMetaObject.connectSlotsByName(pipeline)


        self.Next_Button.clicked.connect(self.Next_Page)

    def retranslateUi(self, pipeline):
        _translate = QtCore.QCoreApplication.translate
        pipeline.setWindowTitle(_translate("pipeline", "pipeline_showcase"))
        self.pushButton.setText(_translate("pipeline", "Next"))


    def Next_Page(self):
        self.window = QtWidgets.QDialog()
        
        # Create an instance of Ui_pipeline and set it up
        self.ui = Ui_pipeline()
        self.ui.setupUi(self.window)

        # Now you can show the QDialog
        self.window.show()

        # Close the current window (optional, if needed)
        self.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pipeline = QtWidgets.QDialog()
    ui = Ui_pipeline()
    ui.setupUi(pipeline)
    pipeline.show()
    sys.exit(app.exec_())
